apiVersion: v1
kind: Pod
metadata:
  name: nginx 
spec:
  containers:
    - image: gcr.io/join-hadoop/nginx:15 
      name: nginx-container 
      volumeMounts:
      - mountPath: /var/log/nginx
        name: test-volume
      type: LoadBalancer
      ports:
      - port: 80
        protocol: TCP
        targetPort: 80
  volumes:
  - name: test-volume
    # This GCE PD must already exist.
    gcePersistentDisk:
      pdName: my-data-disk
      fsType: ext4

